### ISSUE TITLE
Custom video player?

### ISSUE THREAD

**Issue by Manj0tBenipal** [yaswanthkrishna84/kaido#1]
Can you add a custom video player cuz the one in this is outdated

**Comment by yaswanthkrishna84** [comment]
i will try to add

**Comment by Manj0tBenipal** [comment]
Well I guess you won't cuz you copied someone's content. You were not even trying to respect the work by forking it

**Comment by yaswanthkrishna84** [comment]
i am having my final project submission so i hosted it.
i am going to remove it in 10 mins
